glri-catalog-ui/src/main/webapp/templates/contentHome.html

(or it could be a misunderstanding but it still fixes it)

GLRIDB-454 strange bug in  angular solved by superfluous ng-if tag

---

glri-catalog-ui/src/main/webapp/index.jsp

Added a title tag into HTML, not sure it will override Eric's generated title though, we shall see.

title tag try

---

glri-catalog-ui/src/main/webapp/js/app/cida-analytics.js
glri-catalog-ui/src/main/webapp/js/app/controller.js
glri-catalog-ui/src/main/webapp/js/app/nav.js
glri-catalog-ui/src/main/webapp/js/app/sciencebase.js

ga was installed correctly - calls were not. fixed calls to ga and page loads for each Home/Browse/Search should work. Tested with browser console on prod.

GLRIDB-475 ga update

---

glri-catalog-ui/src/main/webapp/js/app/sciencebase.js

unfortunately brittle but case matters and there's a hierarchy for if multiple categories exist.

GLRIDB-494 we don't always want the first category

---

glri-catalog-ui/src/main/webapp/css/glri.css
glri-catalog-ui/src/main/webapp/js/app/sciencebase.js
glri-catalog-ui/src/main/webapp/templates/pager-controls.html

also fixing typo in css
also fixing bug in resource assignment

GLRIDB-378 remove pagination on small views

---

glri-catalog-ui/src/main/webapp/js/app/search.js

can't compare on first category anymore

GLRIDB-494

---

glri-catalog-ui/src/main/webapp/css/glri.css

The project images should respond and resize correctly now on mobile

project images respond correctly

---

glri-catalog-ui/pom.xml
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/itemquery/ScienceBaseAuth.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/itemquery/ScienceBaseQuery.java

* pom has been updated to 1.8
* query class contains a minor refactor/cleanup
* the new ScienceBaseAuth contains the primary code - it will be used with a form to save new projects in ScienceBase.

GLRI-496 Auth via josso

---

glri-catalog-ui/src/main/webapp/js/app/newProjectForm.js

GLRIDB-495 parse contacts

---

glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/itemquery/ScienceBaseProjectService.java
glri-catalog-ui/src/main/webapp/WEB-INF/web.xml
glri-catalog-ui/src/main/webapp/contentProjectForm.html
glri-catalog-ui/src/main/webapp/css/newProjectForm.css
glri-catalog-ui/src/main/webapp/js/app/newProjectForm.js

the java was mostly done in a prior PR, created a servlet to expose and called via ajax, also cleaned up the UI and Angular rendering issue.

GLRIDB-4897 Save New project

---

glri-catalog-ui/src/main/webapp/contentProjectForm.html

Added a title and more help text per input from Alex Covert.

Few more text changes to project form

---

glri-catalog-ui/src/main/webapp/templates/phragmites_management_support.html

The files paths needed an extra . for the files to be found and the table was wider than the wrapper which was causing cutoffs, so made the table fit inside the wrapper

css and dot fix

---

glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/sbapi/ScienceBaseProjectService.java
glri-catalog-ui/src/main/webapp/index.jsp
glri-catalog-ui/src/main/webapp/js/app/main.js
glri-catalog-ui/src/main/webapp/js/app/nav.js
glri-catalog-ui/src/main/webapp/js/app/newProjectForm.js

and comment including error response format

GLRIDB-497 New project form - base url fix

---

glri-catalog-ui/src/main/webapp/js/app/newProjectForm.js
glri-catalog-ui/src/main/webapp/projectForm.jsp
glri-catalog-ui/src/test/js/specs/newProjectForm-spec.js

change image JSON location, manage user name with JOSSO key, default GLRI in the SiGL options

GLRIDB-497 New project form - image url, default value, and user name

---

glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/sbapi/ScienceBaseAuthService.java
glri-catalog-ui/src/main/webapp/js/app/newProjectForm.js

auth was in the url and reverted some of the josso token management

GLRIDB-497 New project form - fix login issue part 2

---

glri-catalog-ui/src/main/webapp/js/app/newProjectForm.js
glri-catalog-ui/src/test/js/specs/newProjectForm-spec.js

fix typoes weblinks to webLinks and Creater to Creator.

GLRIDB-497 New project form - fix typoes

---

glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/AppConfig.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/Format.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/GLRIUtil.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/ParamType.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/ParameterProcessor.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/itemquery/SystemSuppliedParameters.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/itemquery/UserSpecifiedParameters.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/sbapi/ScienceBaseAuthService.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/sbapi/ScienceBaseRestClient.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/vocab/SystemSuppliedParams.java
glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/vocab/UserSpecifiedParams.java

recent release is now sensitive to javadoc issues - cleanup

javadoc cleanup

---

glri-catalog-ui/src/main/java/gov/usgs/cida/glri/sb/ui/sbapi/ScienceBaseProjectService.java
glri-catalog-ui/src/main/webapp/js/app/newProjectForm.js

Improved error logging (server side) and error handling (ui side)

Glridb 504 improve validation for contacts and agencies

---

glri-catalog-ui/src/main/webapp/js/app/newProjectForm.js
glri-catalog-ui/src/main/webapp/projectForm.jsp
glri-catalog-ui/src/test/js/specs/newProjectForm-spec.js

* An email or url is no longer required for an organization
* Fixed a non-related Jasmine test
* Marked the Image URL as a required field and updated its notes (it is currently required, so this is just updating the UI to match the code).

Small validation and UI change

---

glri-catalog-ui/src/main/webapp/js/app/newProjectForm.js
glri-catalog-ui/src/main/webapp/js/app/sciencebase.js
glri-catalog-ui/src/main/webapp/projectForm.jsp
glri-catalog-ui/src/test/js/specs/newProjectForm-spec.js

Please merge GLRIDB-510 (Previous pull Req) first, so that those changes do not show up here.
See comments for the March 14 commit for the actual changes.

Glridb 507 publication list is broken

---

RemoteSingleSignonLogonModule/pom.xml
glri-catalog-jmeter-plugin/pom.xml
glri-catalog-sample-records-script/pom.xml
glri-catalog-ui/pom.xml
glri-catalog-ui/src/main/webapp/css/glri.css
glri-catalog-ui/src/main/webapp/index.jsp
glri-catalog-ui/src/main/webapp/js/app/nav.js
glri-catalog-ui/src/main/webapp/templates/navHome.html

Note that the changes done here were done in a way to explicitly to avoid a larger UI refactor. Ideally I'd like to refactor the Nav service into something a little more structured.

Move publications view into Browse tab

---

glri-catalog-ui/src/main/webapp/index.jsp
glri-catalog-ui/src/main/webapp/js/app/controller.js
glri-catalog-ui/src/main/webapp/js/app/directives.js
glri-catalog-ui/src/main/webapp/js/app/focusAreaManager.js
glri-catalog-ui/src/main/webapp/js/app/main.js
glri-catalog-ui/src/main/webapp/js/app/nav.js
glri-catalog-ui/src/main/webapp/templates/contentPublications.html

projects as there is no obvious way to filter.

Made focus area filtering work for Publications. Currently disbaling for

---

glri-catalog-ui/src/main/webapp/index.jsp
glri-catalog-ui/src/main/webapp/js/app/controller.js

items. Filters return zero results, but that is also the case for search

Reenabled logic to filter pubs by FA. Logic checks both tags and related

---

glri-catalog-ui/src/main/webapp/WEB-INF/web.xml
glri-catalog-ui/src/main/webapp/css/glri.css
glri-catalog-ui/src/main/webapp/secure.jsp
glri-catalog-ui/src/main/webapp/templates/header.jsp

This is a pretty simple implementation, but it works and allows a user to login or logout from any page.
A future added feature would be to preserve the user’s location in the app so they can return to it (probably not worth it).

Added login/logout functionality to the app

---

glri-catalog-ui/src/main/webapp/css/glri.css
glri-catalog-ui/src/main/webapp/js/app/main.js
glri-catalog-ui/src/main/webapp/js/app/newProjectController.js
glri-catalog-ui/src/main/webapp/js/app/sciencebase.js
glri-catalog-ui/src/main/webapp/templates/contentFocusArea.html
glri-catalog-ui/src/main/webapp/templates/project-record.html

Edit links are added when the project has a contact with the same email address of the current user.
Currently the edit link doesn't do anything - Need integration to tie to the edit form.

Added edit links to project search results

---

glri-catalog-ui/src/main/webapp/js/app/directives.js
glri-catalog-ui/src/main/webapp/js/app/focusAreaManager.js
glri-catalog-ui/src/main/webapp/js/app/sciencebase.js
glri-catalog-ui/src/main/webapp/templates/contentFocusArea.html
glri-catalog-ui/src/main/webapp/templates/contentProjectDetail.html

Fixed several issues w/ the edit buttons.  Lots is small issues w/ difference causes.

Wrap-up of edit button issues.

---

glri-catalog-ui/src/main/webapp/css/newProjectForm.css
glri-catalog-ui/src/main/webapp/js/app/newProjectController.js
glri-catalog-ui/src/main/webapp/js/app/projects.js
glri-catalog-ui/src/main/webapp/templates/projectForm.jsp

- some fields cannot be edited
- removed/added "body fields"
- h4 body field validations

UI Updates

---

glri-catalog-ui/src/main/webapp/css/newProjectForm.css
glri-catalog-ui/src/main/webapp/js/app/newProjectController.js
glri-catalog-ui/src/main/webapp/js/app/projects.js
glri-catalog-ui/src/main/webapp/templates/projectForm.jsp

Updated vocabs for spatial and duration to use the new vocabs instead of keyword. Also fixed a small issue where projects would not save properly if there were consecutive commas or trailing commas in the keywords field. Might have merge conflicts with the PT's current PR so don't merge this until after that one has been merged.

GLRIDB-542: Update Spatial Location & Project Duration to Use New Vocabs throughout the app

---

glri-catalog-ui/src/main/webapp/templates/projectForm.jsp

@thongsav-usgs I updated the field descriptions as requested. Let me know if I did this in the wrong place.

Updated descriptions for new fields (GLRI-548).

---

glri-catalog-ui/src/main/webapp/secure.jsp

Switched to a javascript redirect to make sure rewritten context paths
